### ISSUE TITLE
Translate deadzone to xbox

### ISSUE THREAD

**Issue by aleksia123** [Minimuino/thumbstick-deadzones#2]
Nice info on different deadzones. I would like to apply some of the deadzones in a game like halo infinite (xbox). I have a device called cronus max, which is able to set different deadzones from the example script I saw. The programming language for the cronus max is called GPC, which looks like C.

Here is a link to the example script: https://www.consoletuner.com/gpclib/?s=1671 

We could try and enhance this script, or perhaps you know any settings which translate to the most optimal deadzone setting for games like halo infinite

**Comment by Minimuino** [comment]
Hi @aleksia123 , I'm not 100% sure of what you are asking for, but I think I cannot help you with that. I don't know what settings would be the optimal for halo infinite. I guess the only way to find out is to do a lot of testing with different deadzone types.

I'm planning to make a little update for this repo in the upcoming months, but I don't have much time to work on it. If you have an idea to improve the quality of the explanation, or you'd like to add some new concept, you can submit a pull request and I'll be glad to review it, but bear in mind that this repo is just for learning/experimental purpose and it's not focused on any specific game or hardware device.
